version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cellcollective_k12
      POSTGRES_USER: ccadmin
      POSTGRES_PASSWORD: ccpassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - k12-network

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://ccadmin:ccpassword@db:5432/cellcollective_k12
    volumes:
      - .:/app
      - /app/node_modules
      - /app/src/client/node_modules
    depends_on:
      - db
    networks:
      - k12-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/html/public
    depends_on:
      - web
    networks:
      - k12-network

volumes:
  db_data:

networks:
  k12-network:
    driver: bridge
